name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: g++ main.cpp

    - name: Display current directory
      run: dir

    - name: Run the program
      run: ./a.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: TestBinary
        path: ./a.exe
        
